# Generated by Django 6.0.1 on 2026-04-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rating_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='animation_pref',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_directors',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_movie',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='language_pref',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='movie_vibe',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_era',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
