# Generated by Django 6.0.1 on 2026-04-19 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_animation_pref_profile_favorite_directors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='movie_vibe',
        ),
    ]
